// Copyright Koninklijke Philips N.V., 2020. All Right Reserved

#pragma once

#include "Workflow/application.h"
#include "Workflow/datetime.h"
#include "Workflow/event.h"
#include "Workflow/control.h"
#include "Workflow/ireadonlystudyrepository.h"
#include "Workflow/irepository.h"
#include "Workflow/istudyrepository.h"
#include "Workflow/patient.h"
#include "Workflow/personname.h"
#include "Workflow/procedure.h"
#include "Workflow/series.h"
#include "Workflow/settings.h"
#include "Workflow/stringconverter.h"
#include "Workflow/study.h"
#include "Workflow/studyrepository.h"
#include "Workflow/systemsettings.h"
#include "Workflow/ilicense.h"
#include "Workflow/ilicensefactory.h"
#include "Workflow/license.h"
#include "Workflow/licensepluginfactory.h"
#include "Workflow/image.h"
#include "Workflow/imagebuffer.h"
#include "Workflow/istudynotification.h"
#include "Workflow/iprocedurenotification.h"
#include "Workflow/istudyrepositorynotification.h"
#include "Workflow/iseriesnotification.h"
#include "Workflow/inireader.h"
#include "Workflow/iniwriter.h"
#include "Workflow/isystem.h"
#include "Workflow/optional.h"
#include "Workflow/uuid.h"
#include "Workflow/pictorial.h"
#include "Workflow/ipictorialsource.h"