// Copyright Koninklijke Philips N.V., 2020. All Right Reserved

/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/

#pragma once
#include "workflow.h"
#include <Sense.h>
#include <DLS.h>

namespace Test { namespace Binding { namespace Ui {
	
	using namespace Sense;
	using namespace Sense::DLS;
	using namespace Philips::Workflow::Control;

	class View : public Control
	{
	public:

		explicit View(Control &parent, VirtualKeyboard& keyboard)
			:
			Control(parent)
		#pragma region Sense Composer (do not modify)
	,	tab              (*this)
	,	staticsPage      (tab)
	,	label5           (staticsPage)
	,	wstringLabel     (staticsPage)
	,	label2           (staticsPage)
	,	l                (staticsPage)
	,	disableCheckBox  (staticsPage)
	,	radiobutton1     (staticsPage)
	,	radiobutton2     (staticsPage)
	,	radiobutton3     (staticsPage)
	,	button           (staticsPage)
	,	stringLabel      (staticsPage)
	,	intLabel         (staticsPage)
	,	lblName2         (staticsPage)
	,	wstringTouchEditBox(staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	stringTouchEditBox(staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	intTouchEditBox  (staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	hideCheckBox     (staticsPage)
	,	oneWayCheckBox   (staticsPage)
	,	wstringOnewayTouchEditBox(staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	lblName22        (staticsPage)
	,	stringOnewayTouchEditBox(staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	fader            (staticsPage)
	,	faderPage1       (fader)
	,	faderPage2       (fader)
	,	doubleTouchEditBox(staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	doublePrecisionEditBox(staticsPage, keyboard, TouchEditBox::ClearButtonVisible::Auto)
	,	imageBox         (staticsPage)
	,	visibilityButton (staticsPage)
	,	customImageBox   (staticsPage)
	,	intStringLabel   (staticsPage)
	,	listsPage        (tab)
	,	label7           (listsPage)
	,	customListView   (listsPage)
	,	colum1           (customListView)
	,	column2          (customListView)
	,	label3           (listsPage)
	,	stringComboBox   (listsPage)
	,	customComboBox   (listsPage)
	,	label            (listsPage)
	,	onewayComboBox   (listsPage)
	,	customMultiSelectableListView(listsPage)
	,	colum12          (customMultiSelectableListView)
	,	column22         (customMultiSelectableListView)
	,	customOneWayMultiSelectableListView(listsPage)
	,	colum13          (customOneWayMultiSelectableListView)
	,	column23         (customOneWayMultiSelectableListView)
	,	label4           (listsPage)
	,	twowayEditableComboBox(listsPage, keyboard)
	,	visibilityLabel  (listsPage)
	,	panel            (*this)
	,	headerLabel      (panel)
		#pragma endregion
		{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		size                             = Size(1026, 851);
		tab.name                         = L"tab";
		tab.position                     = Point(0, 80);
		tab.size                         = Size(1026, 771);
		tab.font                         = Font(L"CentraleSansMedium", 20, false, false, false, false, Font::Antialias::High, 0);
		tab.background                   = Palette::Gray90;
		tab.headerFont                   = Font(L"CentraleSansMedium", 20, false, false, false, false, Font::Antialias::High, 0);
		tab.headerHeight                 = 64;
		staticsPage.name                 = L"staticsPage";
		staticsPage.layoutSpacing        = 30;
		staticsPage.minimumWidth         = 216;
		label5.position                  = Point(32, 32);
		label5.size                      = Size(200, 48);
		label5.font                      = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		label5.verticalAlign             = VAlign::Middle;
		wstringLabel.name                = L"wstringLabel";
		wstringLabel.position            = Point(256, 32);
		wstringLabel.size                = Size(120, 48);
		wstringLabel.font                = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		wstringLabel.text                = L"";
		wstringLabel.color               = Palette::Gray15;
		wstringLabel.verticalAlign       = VAlign::Middle;
		label2.name                      = L"radiobutton";
		label2.position                  = Point(32, 320);
		label2.size                      = Size(157, 48);
		label2.font                      = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		label2.text                      = L"RadioButton";
		label2.color                     = Palette::Gray15;
		label2.verticalAlign             = VAlign::Middle;
		l.position                       = Point(32, 416);
		l.size                           = Size(192, 48);
		l.font                           = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		l.text                           = L"Check Box";
		l.color                          = Palette::Gray15;
		l.verticalAlign                  = VAlign::Middle;
		disableCheckBox.name             = L"disableCheckBox";
		disableCheckBox.position         = Point(256, 488);
		disableCheckBox.size             = Size(208, 48);
		disableCheckBox.font             = Font(L"CentraleSansMedium", 16, false, false, false, false, Font::Antialias::High, 0);
		disableCheckBox.text             = L"Disable RadioButton 1";
		disableCheckBox.imageSize        = Size(30, 30);
		disableCheckBox.accent           = true;
		radiobutton1.name                = L"radiobutton1";
		radiobutton1.position            = Point(256, 320);
		radiobutton1.size                = Size(200, 48);
		radiobutton1.font                = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		radiobutton1.text                = L"RadioButton 1";
		radiobutton1.accent              = true;
		radiobutton2.name                = L"radiobutton2";
		radiobutton2.position            = Point(480, 320);
		radiobutton2.size                = Size(200, 48);
		radiobutton2.font                = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		radiobutton2.text                = L"RadioButton 2";
		radiobutton2.accent              = true;
		radiobutton3.name                = L"radiobutton3";
		radiobutton3.position            = Point(712, 320);
		radiobutton3.size                = Size(200, 48);
		radiobutton3.font                = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		radiobutton3.visible             = false;
		radiobutton3.enabled             = false;
		radiobutton3.text                = L"RadioButton 3";
		radiobutton3.accent              = true;
		button.name                      = L"button";
		button.position                  = Point(784, 616);
		button.size                      = Size(192, 48);
		button.font                      = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		button.checked                   = true;
		button.text                      = L"Clear TextBox";
		button.accent                    = true;
		stringLabel.name                 = L"stringLabel";
		stringLabel.position             = Point(400, 32);
		stringLabel.size                 = Size(112, 48);
		stringLabel.font                 = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		stringLabel.text                 = L"";
		stringLabel.color                = Palette::Gray15;
		stringLabel.verticalAlign        = VAlign::Middle;
		intLabel.name                    = L"intLabel";
		intLabel.position                = Point(544, 32);
		intLabel.size                    = Size(112, 48);
		intLabel.font                    = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		intLabel.text                    = L"";
		intLabel.color                   = Palette::Gray15;
		intLabel.verticalAlign           = VAlign::Middle;
		lblName2.name                    = L"lblName2";
		lblName2.position                = Point(32, 128);
		lblName2.size                    = Size(200, 48);
		lblName2.font                    = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		lblName2.text                    = L"Touch Edit Box";
		lblName2.color                   = Palette::Gray15;
		lblName2.verticalAlign           = VAlign::Middle;
		//wstringTouchEditBox.composerClass = EditBox;
		wstringTouchEditBox.name         = L"wstringTouchEditBox";
		wstringTouchEditBox.position     = Point(256, 128);
		wstringTouchEditBox.size         = Size(104, 48);
		wstringTouchEditBox.font         = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		wstringTouchEditBox.maxLength    = 2;
		wstringTouchEditBox.margin       = Margin(12, 0, 40, 0);
		wstringTouchEditBox.filter       = L"0123456789";
		//stringTouchEditBox.composerClass = EditBox;
		stringTouchEditBox.name          = L"stringTouchEditBox";
		stringTouchEditBox.position      = Point(408, 128);
		stringTouchEditBox.size          = Size(104, 48);
		stringTouchEditBox.font          = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		stringTouchEditBox.maxLength     = 2;
		stringTouchEditBox.margin        = Margin(12, 0, 40, 0);
		stringTouchEditBox.filter        = L"0123456789";
		//intTouchEditBox.composerClass  = EditBox;
		intTouchEditBox.name             = L"intTouchEditBox";
		intTouchEditBox.position         = Point(568, 128);
		intTouchEditBox.size             = Size(104, 48);
		intTouchEditBox.font             = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		intTouchEditBox.maxLength        = 2;
		intTouchEditBox.margin           = Margin(12, 0, 40, 0);
		intTouchEditBox.filter           = L"0123456789";
		hideCheckBox.name                = L"hideCheckBox";
		hideCheckBox.position            = Point(480, 488);
		hideCheckBox.size                = Size(200, 48);
		hideCheckBox.font                = Font(L"CentraleSansMedium", 16, false, false, false, false, Font::Antialias::High, 0);
		hideCheckBox.text                = L"Hide Radio Button 2";
		hideCheckBox.imageSize           = Size(30, 30);
		hideCheckBox.accent              = true;
		oneWayCheckBox.name              = L"oneWayCheckBox";
		oneWayCheckBox.position          = Point(256, 416);
		oneWayCheckBox.size              = Size(208, 48);
		oneWayCheckBox.font              = Font(L"CentraleSansMedium", 16, false, false, false, false, Font::Antialias::High, 0);
		oneWayCheckBox.text              = L"OneWay CheckBox";
		oneWayCheckBox.imageSize         = Size(30, 30);
		oneWayCheckBox.accent            = true;
		//wstringOnewayTouchEditBox.composerClass = EditBox;
		wstringOnewayTouchEditBox.name   = L"wstringOnewayTouchEditBox";
		wstringOnewayTouchEditBox.position = Point(256, 216);
		wstringOnewayTouchEditBox.size   = Size(200, 48);
		wstringOnewayTouchEditBox.font   = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		wstringOnewayTouchEditBox.maxLength = 2;
		wstringOnewayTouchEditBox.margin = Margin(12, 0, 40, 0);
		wstringOnewayTouchEditBox.filter = L"0123456789";
		lblName22.name                   = L"lblName22";
		lblName22.position               = Point(32, 216);
		lblName22.size                   = Size(200, 48);
		lblName22.font                   = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		lblName22.text                   = L"Oneway Touch Edit Box";
		lblName22.color                  = Palette::Gray15;
		lblName22.verticalAlign          = VAlign::Middle;
		//stringOnewayTouchEditBox.composerClass = EditBox;
		stringOnewayTouchEditBox.name    = L"stringOnewayTouchEditBox";
		stringOnewayTouchEditBox.position = Point(480, 216);
		stringOnewayTouchEditBox.size    = Size(200, 48);
		stringOnewayTouchEditBox.font    = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		stringOnewayTouchEditBox.maxLength = 2;
		stringOnewayTouchEditBox.margin  = Margin(12, 0, 40, 0);
		stringOnewayTouchEditBox.filter  = L"0123456789";
		fader.name                       = L"fader";
		fader.position                   = Point(32, 576);
		fader.size                       = Size(656, 88);
		faderPage1.name                  = L"faderPage1";
		faderPage1.color                 = Palette::S_Indigo60;
		faderPage2.name                  = L"faderPage2";
		faderPage2.color                 = Palette::S_Green60;
		//doubleTouchEditBox.composerClass = EditBox;
		doubleTouchEditBox.name          = L"doubleTouchEditBox";
		doubleTouchEditBox.position      = Point(728, 128);
		doubleTouchEditBox.size          = Size(104, 48);
		doubleTouchEditBox.font          = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		doubleTouchEditBox.maxLength     = 2;
		doubleTouchEditBox.margin        = Margin(12, 0, 40, 0);
		doubleTouchEditBox.filter        = L"0123456789";
		//doublePrecisionEditBox.composerClass = EditBox;
		doublePrecisionEditBox.name      = L"doublePrecisionEditBox";
		doublePrecisionEditBox.position  = Point(880, 128);
		doublePrecisionEditBox.size      = Size(104, 48);
		doublePrecisionEditBox.font      = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		doublePrecisionEditBox.maxLength = 2;
		doublePrecisionEditBox.margin    = Margin(12, 0, 40, 0);
		doublePrecisionEditBox.filter    = L"0123456789";
		imageBox.name                    = L"imageBox";
		imageBox.position                = Point(816, 392);
		imageBox.size                    = Size(112, 104);
		visibilityButton.name            = L"visibilityButton";
		visibilityButton.position        = Point(816, 528);
		visibilityButton.size            = Size(128, 48);
		customImageBox.name              = L"customImageBox";
		customImageBox.position          = Point(624, 384);
		customImageBox.size              = Size(112, 96);
		intStringLabel.name              = L"intStringLabel";
		intStringLabel.position          = Point(688, 32);
		intStringLabel.size              = Size(112, 48);
		intStringLabel.font              = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		intStringLabel.text              = L"";
		intStringLabel.color             = Palette::Gray15;
		intStringLabel.verticalAlign     = VAlign::Middle;
		listsPage.name                   = L"listsPage";
		listsPage.minimumWidth           = 240;
		label7.position                  = Point(32, 320);
		label7.size                      = Size(280, 48);
		label7.font                      = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		label7.text                      = L"ListView";
		label7.verticalAlign             = VAlign::Middle;
		customListView.name              = L"customListView";
		customListView.position          = Point(32, 384);
		customListView.size              = Size(344, 288);
		customListView.font              = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		customListView.area              = Size(344, 480);
		customListView.showHorizontalBar = ScrollAreaBase::ShowState::Hide;
		customListView.color             = Palette::Gray85;
		customListView.itemHeight        = 48;
		colum1.name                      = L"colum1";
		colum1.size                      = Size(184, 48);
		colum1.font                      = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		colum1.resizable                 = false;
		colum1.movable                   = false;
		colum1.clickable                 = false;
		colum1.cellImageSpacing          = 16;
		colum1.text                      = L"Column 1";
		column2.name                     = L"column2";
		column2.size                     = Size(160, 48);
		column2.font                     = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		column2.resizable                = false;
		column2.movable                  = false;
		column2.clickable                = false;
		column2.text                     = L"Column 2";
		label3.position                  = Point(32, 32);
		label3.size                      = Size(168, 48);
		label3.font                      = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		label3.text                      = L"ComboBox";
		label3.color                     = Palette::Gray15;
		label3.verticalAlign             = VAlign::Middle;
		stringComboBox.name              = L"stringComboBox";
		stringComboBox.position          = Point(32, 96);
		stringComboBox.size              = Size(280, 48);
		stringComboBox.font              = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		stringComboBox.noActivate        = true;
		stringComboBox.buttonWidth       = 48;
		stringComboBox.arrowWidth        = 10;
		stringComboBox.itemHeight        = 22;
		stringComboBox.textMargin        = Margin(16, 0, 8, 0);
		customComboBox.name              = L"customComboBox";
		customComboBox.position          = Point(360, 96);
		customComboBox.size              = Size(280, 48);
		customComboBox.font              = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		customComboBox.noActivate        = true;
		customComboBox.buttonWidth       = 48;
		customComboBox.arrowWidth        = 10;
		customComboBox.itemHeight        = 22;
		customComboBox.textMargin        = Margin(16, 0, 8, 0);
		label.position                   = Point(32, 168);
		label.size                       = Size(168, 48);
		label.font                       = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		label.text                       = L"Oneway ComboBox";
		label.color                      = Palette::Gray15;
		label.verticalAlign              = VAlign::Middle;
		onewayComboBox.name              = L"onewayComboBox";
		onewayComboBox.position          = Point(32, 232);
		onewayComboBox.size              = Size(280, 48);
		onewayComboBox.font              = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		onewayComboBox.noActivate        = true;
		onewayComboBox.buttonWidth       = 48;
		onewayComboBox.arrowWidth        = 10;
		onewayComboBox.itemHeight        = 22;
		onewayComboBox.textMargin        = Margin(16, 0, 8, 0);
		customMultiSelectableListView.name = L"customMultiSelectableListView";
		customMultiSelectableListView.position = Point(384, 384);
		customMultiSelectableListView.size = Size(312, 288);
		customMultiSelectableListView.font = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		customMultiSelectableListView.area = Size(296, 480);
		customMultiSelectableListView.showHorizontalBar = ScrollAreaBase::ShowState::Hide;
		customMultiSelectableListView.multiselect = true;
		customMultiSelectableListView.toggleClick = true;
		customMultiSelectableListView.color = Palette::Gray85;
		customMultiSelectableListView.itemHeight = 48;
		colum12.name                     = L"colum12";
		colum12.size                     = Size(114, 48);
		colum12.font                     = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		colum12.resizable                = false;
		colum12.movable                  = false;
		colum12.clickable                = false;
		colum12.cellImageSpacing         = 16;
		colum12.text                     = L"Column 1";
		column22.name                    = L"column22";
		column22.size                    = Size(112, 48);
		column22.font                    = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		column22.resizable               = false;
		column22.movable                 = false;
		column22.clickable               = false;
		column22.text                    = L"Column 2";
		customOneWayMultiSelectableListView.name = L"customOneWayMultiSelectableListView";
		customOneWayMultiSelectableListView.position = Point(712, 384);
		customOneWayMultiSelectableListView.size = Size(312, 288);
		customOneWayMultiSelectableListView.font = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		customOneWayMultiSelectableListView.area = Size(296, 480);
		customOneWayMultiSelectableListView.showHorizontalBar = ScrollAreaBase::ShowState::Hide;
		customOneWayMultiSelectableListView.multiselect = true;
		customOneWayMultiSelectableListView.toggleClick = true;
		customOneWayMultiSelectableListView.color = Palette::Gray85;
		customOneWayMultiSelectableListView.itemHeight = 48;
		colum13.name                     = L"colum13";
		colum13.size                     = Size(106, 48);
		colum13.font                     = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		colum13.resizable                = false;
		colum13.movable                  = false;
		colum13.clickable                = false;
		colum13.cellImageSpacing         = 16;
		colum13.text                     = L"Column 1";
		column23.name                    = L"column23";
		column23.size                    = Size(112, 48);
		column23.font                    = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		column23.resizable               = false;
		column23.movable                 = false;
		column23.clickable               = false;
		column23.text                    = L"Column 2";
		label4.position                  = Point(392, 168);
		label4.size                      = Size(232, 48);
		label4.font                      = Font(L"CentraleSansMedium", 16, false, false, false, false, Font::Antialias::High, 0);
		label4.text                      = L"Twoway EditableComboBox";
		label4.horizontalAlign           = HAlign::Center;
		label4.verticalAlign             = VAlign::Middle;
		//twowayEditableComboBox.composerClass = Control;
		twowayEditableComboBox.name      = L"TwowayEditableComboBox";
		twowayEditableComboBox.position  = Point(392, 232);
		twowayEditableComboBox.size      = Size(280, 48);
		twowayEditableComboBox.font      = Font(L"CentraleSansDS Light", 16, false, false, false, false, Font::Antialias::High, 0);
		twowayEditableComboBox.tabStop   = true;
		twowayEditableComboBox.noActivate = true;
		visibilityLabel.name             = L"visibilityLabel";
		visibilityLabel.position         = Point(760, 304);
		visibilityLabel.size             = Size(200, 48);
		panel.size                       = Size(1026, 80);
		panel.colorShadow                = Palette::Black * 0.50;
		panel.color                      = Palette::Gray75;
		headerLabel.name                 = L"headerLabel";
		headerLabel.position             = Point(24, 0);
		headerLabel.size                 = Size(1002, 80);
		headerLabel.font                 = Font(L"CentraleSansBold", 24, false, false, false, false, Font::Antialias::High, 0);
		headerLabel.text                 = L"";
		headerLabel.color                = Palette::Gray15;
		headerLabel.verticalAlign        = VAlign::Middle;
		layoutUpdateEnd();
		#pragma endregion
		}

	#pragma region Sense Composer (do not modify)
	public:    Tab               tab;
	public:    TabPage           staticsPage;
	private:   Label             label5;
	public:    Label             wstringLabel;
	private:   Label             label2;
	private:   Label             l;
	public:    CheckBox          disableCheckBox;
	public:    RadioButton       radiobutton1;
	public:    RadioButton       radiobutton2;
	public:    RadioButton       radiobutton3;
	public:    Button            button;
	public:    Label             stringLabel;
	public:    Label             intLabel;
	public:    Label             lblName2;
	public:    TouchEditBox      wstringTouchEditBox;
	public:    TouchEditBox      stringTouchEditBox;
	public:    TouchEditBox      intTouchEditBox;
	public:    CheckBox          hideCheckBox;
	public:    CheckBox          oneWayCheckBox;
	public:    TouchEditBox      wstringOnewayTouchEditBox;
	public:    Label             lblName22;
	public:    TouchEditBox      stringOnewayTouchEditBox;
	public:    Fader             fader;
	public:    FaderPage         faderPage1;
	public:    FaderPage         faderPage2;
	public:    TouchEditBox      doubleTouchEditBox;
	public:    TouchEditBox      doublePrecisionEditBox;
	public:    ImageBox          imageBox;
	public:    Button            visibilityButton;
	public:    ImageBox          customImageBox;
	public:    Label             intStringLabel;
	public:    TabPage           listsPage;
	private:   Label             label7;
	public:    ListView          customListView;
	public:    ListViewHeader    colum1;
	public:    ListViewHeader    column2;
	private:   Label             label3;
	public:    ComboBox          stringComboBox;
	public:    ComboBox          customComboBox;
	private:   Label             label;
	public:    ComboBox          onewayComboBox;
	public:    ListView          customMultiSelectableListView;
	public:    ListViewHeader    colum12;
	public:    ListViewHeader    column22;
	public:    ListView          customOneWayMultiSelectableListView;
	public:    ListViewHeader    colum13;
	public:    ListViewHeader    column23;
	private:   Label             label4;
	public:    EditableComboBox  twowayEditableComboBox;
	public:    Label             visibilityLabel;
	private:   Panel             panel;
	public:    Label             headerLabel;
	#pragma endregion

	private:

		View(const View&);
		View& operator=(const View&);
	};

}}}
