/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <DLS.h>

using namespace Sense;
using namespace Sense::DLS;

namespace Philips {namespace Workflow {namespace Control {namespace Ui {
	class BannerTsm : public Spacer
	{
	public:

		BannerTsm(Control &parent)
			:
			Spacer(parent)
		#pragma region Sense Composer (do not modify)
	,	separator        (*this)
	,	buttonCustom     (*this)
		#pragma endregion
		{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		name                             = L"BannerTsm";
		size                             = Size(1280, 42);
		visible                          = false;
		enabled                          = false;
		separator.name                   = L"separator";
		separator.size                   = Size(1280, 8);
		separator.noActivate             = true;
		separator.color1                 = Palette::S_Green45;
		separator.width                  = 4;
		buttonCustom.name                = L"buttonCustom";
		buttonCustom.position            = Point(512, 0);
		buttonCustom.size                = Size(286, 40);
		buttonCustom.font                = Font(L"CentraleSansBook", 20, true, false, false, false, Font::Antialias::High, 0);
		buttonCustom.text                = L"";
		buttonCustom.radius              = Corners(2, 2, 4, 4);
		buttonCustom.textType            = TextType::SingleLine;
		buttonCustom.colorFontUp         = Palette::Green90;
		buttonCustom.colorFontDown       = Palette::Green90;
		buttonCustom.colorFontHover      = Palette::Green90;
		buttonCustom.colorFontDisabled   = Palette::Green90;
		buttonCustom.colorButtonUp       = Palette::S_Green45;
		buttonCustom.colorButtonDown     = Palette::S_Green45;
		buttonCustom.colorButtonHover    = Palette::S_Green45;
		buttonCustom.colorButtonDisabled = Palette::S_Green45;
		layoutUpdateEnd();
		#pragma endregion
		}

	#pragma region Sense Composer (do not modify)
	public:    Separator         separator;
	public:    ButtonCustom      buttonCustom;
	#pragma endregion

	private:

		BannerTsm(const BannerTsm&) = delete;
		BannerTsm& operator=(const BannerTsm&) = delete;
	};
}}}}

