// Copyright Koninklijke Philips N.V., 2020. All Right Reserved

/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include "scrollablelabel.ui.h"
#include <Sense.h>
#include <DLS.h>

namespace Philips { namespace Workflow { namespace Control { namespace Ui {
	
	using namespace Sense;
	using namespace Sense::DLS;
	
	class DialogBoxIntegrated : public Dialog
	{
	public:
	
		DialogBoxIntegrated(Control &parent)
		:
			Dialog(parent)
		#pragma region Sense Composer (do not modify)
	,	opacityBuffer    (*this)
	,	headerSpacer     (opacityBuffer)
	,	message          (opacityBuffer)
	,	bodySpacer       (opacityBuffer)
	,	description      (opacityBuffer)
	,	footerSpacer     (opacityBuffer)
	,	footer           (opacityBuffer)
	,	space            ((Control&)footer)
	,	third            (footer)
	,	cancel           (footer)
	,	ok               (footer)
	,	bottomSpacer     (opacityBuffer)
		#pragma endregion
		{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		name                             = L"dialogMessage";
		size                             = Size(800, 196);
		font                             = Font(L"CentraleSansBook", 20, false, false, false, false, Font::Antialias::High, 0);
		layoutSpacing                    = 0;
		headerSize                       = 12;
		radius                           = Corners(4, 4, 4, 4);
		shadow                           = Margin(10, 10, 20, 20);
		colorShadow                      = Palette::Black * 0.35;
		colorHeader                      = Color::fromRgb(43, 174, 254);
		colorFont                        = Palette::White;
		color                            = Palette::Gray70;
		headerFont                       = Font(L"CentraleSansBold", 32, false, false, false, false, Font::Antialias::High, 0);
		text                             = L"";
		textMargin                       = Margin(48, 0, 24, 0);
		opacityBuffer.name               = L"opacityBuffer";
		opacityBuffer.size               = Size(800, 184);
		opacityBuffer.layout             = Layout::Fill;
		opacityBuffer.layoutSpacing      = 0;
		headerSpacer.name                = L"headerSpacer";
		headerSpacer.size                = Size(800, 28);
		headerSpacer.layout              = Layout::Fixed1d;
		message.name                     = L"message";
		message.position                 = Point(24, 28);
		message.size                     = Size(752, 24);
		message.font                     = Font(L"CentraleSans Bold", 20, false, false, false, false, Font::Antialias::High, 0);
		message.layout                   = Layout::Fixed1d;
		message.layoutOuterMargin        = Margin(24, 0, 24, 0);
		message.text                     = L"";
		message.color                    = Palette::White;
		message.verticalAlign            = VAlign::Middle;
		bodySpacer.name                  = L"bodySpacer";
		bodySpacer.position              = Point(0, 52);
		bodySpacer.size                  = Size(800, 20);
		bodySpacer.layout                = Layout::Fixed1d;
		description.name                 = L"description";
		description.position             = Point(24, 72);
		description.size                 = Size(752, 0);
		description.font                 = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		description.layout               = Layout::Fixed1d;
		description.layoutOuterMargin    = Margin(24, 0, 24, 0);
		footerSpacer.name                = L"footerSpacer";
		footerSpacer.position            = Point(0, 72);
		footerSpacer.size                = Size(800, 32);
		footerSpacer.layout              = Layout::Fixed1d;
		footer.name                      = L"Footer";
		footer.position                  = Point(0, 104);
		footer.size                      = Size(800, 40);
		footer.layout                    = Layout::Fixed1d;
		footer.layoutInnerMargin         = Margin(0, 0, 12, 0);
		footer.layoutOrientation         = Orientation::Horizontal;
		space.name                       = L"space";
		space.position                   = Point(8, 0);
		space.size                       = Size(284, 40);
		space.layout                     = Layout::Fill;
		space.layoutOuterMargin          = Margin(8, 0, 0, 0);
		third.name                       = L"third";
		third.position                   = Point(300, 0);
		third.size                       = Size(160, 40);
		third.font                       = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		third.layout                     = Layout::Fixed1d;
		third.text                       = L"";
		third.textMargin                 = Margin(16, 4, 16, 4);
		third.textType                   = TextType::SingleLine;
		third.colorFontUp                = Palette::White;
		third.colorFontDown              = Palette::White;
		third.colorFontHover             = Palette::White;
		third.colorFontDisabled          = Palette::White * 0.50;
		third.colorButtonUp              = Palette::Gray45;
		third.colorButtonDown            = Palette::Gray55;
		third.colorButtonHover           = Palette::Gray50;
		third.colorButtonDisabled        = Palette::Gray45 * 0.35;
		cancel.name                      = L"cancel";
		cancel.position                  = Point(468, 0);
		cancel.size                      = Size(160, 40);
		cancel.font                      = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		cancel.layout                    = Layout::Fixed1d;
		cancel.text                      = L"";
		cancel.textMargin                = Margin(16, 4, 16, 4);
		cancel.textType                  = TextType::SingleLine;
		cancel.colorFontUp               = Palette::White;
		cancel.colorFontDown             = Palette::White;
		cancel.colorFontHover            = Palette::White;
		cancel.colorFontDisabled         = Palette::White * 0.50;
		cancel.colorButtonUp             = Palette::Gray45;
		cancel.colorButtonDown           = Palette::Gray55;
		cancel.colorButtonHover          = Palette::Gray50;
		cancel.colorButtonDisabled       = Palette::Gray45 * 0.35;
		ok.name                          = L"ok";
		ok.position                      = Point(636, 0);
		ok.size                          = Size(160, 40);
		ok.font                          = Font(L"CentraleSansBook", 16, false, false, false, false, Font::Antialias::High, 0);
		ok.layout                        = Layout::Fixed1d;
		ok.checked                       = true;
		ok.text                          = L"";
		ok.textMargin                    = Margin(16, 4, 16, 4);
		ok.textType                      = TextType::SingleLine;
		ok.accent                        = true;
		ok.colorFontUp                   = Palette::White;
		ok.colorFontDown                 = Palette::White;
		ok.colorFontHover                = Palette::White;
		ok.colorFontDisabled             = Palette::White * 0.50;
		ok.colorFocusUp                  = Palette::Blue60;
		ok.colorFocusDown                = Palette::Blue50;
		ok.colorFocusHover               = Palette::Blue55;
		ok.colorFocusDisabled            = Palette::Blue60 * 0.35;
		bottomSpacer.name                = L"BottomSpacer";
		bottomSpacer.position            = Point(0, 144);
		bottomSpacer.size                = Size(800, 12);
		bottomSpacer.layout              = Layout::Fixed1d;
		layoutUpdateEnd();
		#pragma endregion
		}
	
	#pragma region Sense Composer (do not modify)
	public:    Buffer            opacityBuffer;
	public:    Spacer            headerSpacer;
	public:    Label             message;
	public:    Spacer            bodySpacer;
	public:    ScrollableLabel   description;
	public:    Spacer            footerSpacer;
	public:    Control           footer;
	public:    Control           space;
	public:    ButtonCustom      third;
	public:    ButtonCustom      cancel;
	public:    ButtonCustom      ok;
	public:    Spacer            bottomSpacer;
	#pragma endregion
	
	private:
	
		DialogBoxIntegrated(const DialogBoxIntegrated&);
		DialogBoxIntegrated& operator=(const DialogBoxIntegrated&);
	};
	
}}}}

