/*----------------------------------------------------
 |   This file was generated by Sense Composer 2.0   |
 |  Do not modify the Sense Composer Generated Code  |
 ----------------------------------------------------*/
#pragma once

#include <Sense.h>
#include <DLS.h>

namespace Philips { namespace Workflow { namespace Control { namespace Ui {

using namespace Sense;
using namespace Sense::DLS;

class ScrollableLabel : public Control
{
public:

	ScrollableLabel(Control &parent)
	:
		Control(parent)
		#pragma region Sense Composer (do not modify)
	,	scrollArea       (*this)
	,	text             (scrollArea)
		#pragma endregion
	{
		#pragma region Sense Composer (do not modify)
		layoutUpdateBegin();
		size                             = Size(752, 24);
		scrollArea.name                  = L"scrollArea";
		scrollArea.size                  = Size(750, 24);
		scrollArea.area                  = Size(750, 24);
		scrollArea.showHorizontalBar     = ScrollAreaBase::ShowState::Hide;
		scrollArea.shadowColor           = Palette::GroupBlue65;
		scrollArea.transparent           = false;
		text.name                        = L"text";
		text.size                        = Size(736, 24);
		text.text                        = L"";
		text.textType                    = TextType::WordWrap;
		layoutUpdateEnd();
		#pragma endregion
	}

	#pragma region Sense Composer (do not modify)
	public:    ScrollArea        scrollArea;
	public:    Label             text;
	#pragma endregion
private:
	ScrollableLabel(const ScrollArea&) 			    = delete;
	ScrollableLabel& operator=(const ScrollArea&) 	= delete;
};

}}}}